[workspace]
members = [
    "cli",
    "commands",
    "fs",
    "shared"
]

build = "build.rs"

[package]
name = "twist"
version = "0.1.0"
edition = "2021"

[dependencies]
twist_cli =  { path = "./cli" }
twist_commands =  { path = "./commands" }
anyhow = "1.0"
git2 = "0.13"
log = "0.4"
openssl = "0.10"
thiserror = "1.0"
toml = "0.5"

[build-dependencies]
twist_cli =  { path = "./cli" }
clap = "3"
clap_derive = "3"
clap_complete = "3"

