[workspace]
members = [
    "cli",
    "commands",
    "common"
]

[package]
name = "twist"
version = "0.1.1"
edition = "2021"
build = "build.rs"

[dependencies]
twist-cli =  { path = "./cli" }
twist-commands =  { path = "./commands" }
anyhow = "1.0"
git2 = "0.14"
log = "0.4"
openssl = "0.10"
thiserror = "1.0"
toml = "0.5"

[build-dependencies]
twist-cli =  { path = "./cli" }
clap = "3"
clap_derive = "3"
clap_complete = "3"
