[workspace]
members = [
    "cli",
    "fs",
    "shared"
]

build = "build.rs"

[package]
name = "twist"
version = "0.1.0"
edition = "2021"

[dependencies]
twist_cli =  { path = "./cli" }
twist_fs =  { path = "./fs" }
twist_shared =  { path = "./shared" }
anyhow = "1.0"
dirs = "3.0"
git2 = "0.13"
glob = "0.3"
log = "0.4"
openssl = "0.10"
rust-crypto = "0.2"
simplelog = "0.11"
thiserror = "1.0"
toml = "0.5"

[build-dependencies]
twist_cli =  { path = "./cli" }
clap = "3"
clap_derive = "3"
clap_complete = "3"

