[package]
name = "twist"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
dirs = "3.0"
git2 = "0.13"
glob = "0.3"
log = "0.4"
openssl = "0.10"
rust-crypto = "0.2"
serde =  { version = "1.0", features = ["derive"] }
simplelog = "0.11"
structopt = "0.3"
strum = "0.24"
strum_macros = "0.24"
thiserror = "1.0"
toml = "0.5"
