[package]
name = "twist_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twist_shared = { path = "../shared" }
anyhow = "1.0"
clap = { version = "3.1", features = ["derive", "env"] }
dirs = "4.0"
simplelog = "0.11"
thiserror = "1.0"
