[package]
name = "twist_fs"
version = "0.1.0"
edition = "2021"

[dependencies]
twist_shared = { path = "../shared" }
anyhow = "1.0"
chrono = "0.4"
dirs = "4.0"
git2 = "0.14"
log = "0.4"
openssl = "0.10"
glob = "0.3"
thiserror = "1.0"

[dev-dependencies]
faux = "^0.1"