[package]
name = "twist-common"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
dirs = "4.0"
fs_extra = "1.2"
git2 = "0.14"
glob = "0.3"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
openssl = "0.10"
toml = "0.5"